language: rust
cache:
- cargo
before_install:
install:
- source ~/.cargo/env || true
- bash ci/install.sh
script:
- mdbook build
- mdbook test
notifications:
  email:
    on_success: never
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book
  on:
    branch: translation
branches:
  only:
    - translation
