[book]
title = "プログラミング言語 Rust"
author = ["Toshihiko Ryugo @SIVIRA", "Motoki Sato @SIVIRA"]
src = "src-ja"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
